version: '3'
services:
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      PUID: 1000
      MONGO_INITDB_DATABASE: mongodb
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: app
    container_name: app
    restart: "no"
    depends_on:
      - "mongodb"
    links:
      - mongodb
    ports:
      - "80:8080"
    environment:
      SPRING_DATA_MONGODB_DATABASE: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb
